// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShList.Persistance.ORM;

namespace ShList.Persistance.Migrations
{
    [DbContext(typeof(ShoppingListContext))]
    partial class ShoppingListContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShList.Domain.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("ShList.Domain.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ShList.Domain.Models.Shop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Shop");
                });

            modelBuilder.Entity("ShList.Domain.Models.ShoppingList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ShoppingLists");
                });

            modelBuilder.Entity("ShList.Domain.Models.ShoppingList", b =>
                {
                    b.OwnsMany("ShList.Domain.Models.ShItem", "_items", b1 =>
                        {
                            b1.Property<Guid>("ShoppingListId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("DepartmentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("ShopId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Status")
                                .HasColumnType("int");

                            b1.HasKey("ShoppingListId", "Id");

                            b1.HasIndex("DepartmentId");

                            b1.HasIndex("ProductId");

                            b1.HasIndex("ShopId");

                            b1.ToTable("ShItem");

                            b1.HasOne("ShList.Domain.Models.Department", "Department")
                                .WithMany()
                                .HasForeignKey("DepartmentId");

                            b1.HasOne("ShList.Domain.Models.Product", "Product")
                                .WithMany()
                                .HasForeignKey("ProductId");

                            b1.HasOne("ShList.Domain.Models.Shop", "Shop")
                                .WithMany()
                                .HasForeignKey("ShopId");

                            b1.WithOwner()
                                .HasForeignKey("ShoppingListId");

                            b1.OwnsOne("ShList.Domain.Models.ShItem+ShIQuantity", "Quantity", b2 =>
                                {
                                    b2.Property<Guid>("ShItemShoppingListId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("ShItemId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.HasKey("ShItemShoppingListId", "ShItemId");

                                    b2.ToTable("ShItem");

                                    b2.WithOwner()
                                        .HasForeignKey("ShItemShoppingListId", "ShItemId");
                                });

                            b1.Navigation("Department");

                            b1.Navigation("Product");

                            b1.Navigation("Quantity");

                            b1.Navigation("Shop");
                        });

                    b.Navigation("_items");
                });
#pragma warning restore 612, 618
        }
    }
}
